keys:
  - &users:
    - &user 0581367C097C635BF5839E57282872FA4AF162DE
  - &homes:
    - &user_home age1fqgqugs3xk430tleutumc6ppk3l26expcszhhn4l0d3p7erf2ses5neg2j
  - &hosts:
    - &thinkpadx1 age1s9t5rzd5rtnlvjqleyuuw7gpcxyxv0q7lrm9hx0y7pcg20z9dqkqy3zvv6
    - &asrock age1jgfvjm4l78e8gg0e3k29xy74dtutegayy0wzeeqk2jvtt6mahsqq6p7uy7
    - &malthor age1p29ylk2c34e336mlfe24u7qh0eel4cxefn469qtq2whm9nlgv95qkc00zv
creation_rules:
  - path_regex: hosts/components(/users)?/secrets.yml$
    key_groups:
      - age:
        - *thinkpadx1
        - *asrock
        - *malthor
        - *user_home
        pgp:
          - *user
  - path_regex: home/user/components/secrets.yml$
    key_groups:
      - age:
          - *user_home
        pgp:
          - *user
